### ISSUE TITLE
Unable to resolve "moment" from "node_modules\react-native-simple-alarm\src\helpers\activateAlarm.js"

### ISSUE THREAD

**Issue by nicholascwz** [liplylie/react-native-simple-alarm#1]
Hi, I'm getting this error when trying to run.  

Unable to resolve "moment" from "node_modules\react-native-simple-alarm\src\helpers\activateAlarm.js"

Any idea how I can rectify this? 

Thanks

**Comment by liplylie** [comment]
This may have been caused by moment being added as a devDependency in package.json. Added to dependencies in 1.0.3
