### ISSUE TITLE
Native module cannot be null

### ISSUE THREAD

**Issue by panda0603** [liplylie/react-native-simple-alarm#2]
Hello, 

I just copied the code from the example, tried to run on fresh new project, 

I get 'Native module cannot be null' error in iOS. 

I guess it  is the createAlarm function that is causing the problem since when I comment it out, error disappears

**Comment by liplylie** [comment]
@panda0603 Are you referring to `createAlarm` in `example/src/Home/AddAlarms.js`?

**Comment by liplylie** [comment]
@panda0603 It worked for me.

Did you make sure to run pod install? 

https://stackoverflow.com/questions/38698657/react-native-native-module-cannot-be-null

**Comment by panda0603** [comment]
yes I did do pod install, didn't work. 
I had to do extra step. 
The solution was to install @react-native-community/push-notification-ios, and do pod install for that.

**Comment by liplylie** [comment]
This may be due to `@react-native-community/push-notification-ios` being added under devDependencies, instead of dependencies. Just pushed up a fix.

Thank you for reporting this issue!
