### ISSUE TITLE
Scheduled notifications limit

### ISSUE THREAD

**Issue by douglasjunior** [liplylie/react-native-simple-alarm#26]
Hi! First, thank you for this library!

Last year I worked on a project with the need to create alarms, but I found this limitation: https://developer.apple.com/documentation/uikit/uilocalnotification

> An app can have only a limited number of scheduled notifications; the system keeps the soonest-firing 64 notifications (with automatically rescheduled notifications counting as a single notification) and discards the rest.

How was this handled here in this library?

**Comment by liplylie** [comment]
Hi Douglas, thank you for the comment.

Alarms with `active === false` will not have a scheduled notification set. The alarm will actually just be stored in AsyncStorage and not set as a push notification. Once set to `active === true`, then a scheduled push notification will be created.

However, If the user has 64 alarms with `active === true`, then there is nothing that can be done. I should actually add a condition saying the max number of active alarms is 64.

**Comment by douglasjunior** [comment]
Got it, thanks for the reply!
