### ISSUE TITLE
Can't build Example 

### ISSUE THREAD

**Issue by alexchudnovsky** [liplylie/react-native-simple-alarm#30]
Hi,

I am trying to build the example project but having the errors below

Wondering if someone could please help 

alexchudnovsky:example/ $ npm install                                                                                                                                                                  [18:36:54]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: react-native-simple-alarm-example@0.0.3
npm ERR! Found: react@16.11.0
npm ERR! node_modules/react
npm ERR!   react@"16.11.0" from the root project
npm ERR!   peer react@"^16.8" from @react-native-community/async-storage@1.12.1
npm ERR!   node_modules/@react-native-community/async-storage
npm ERR!     @react-native-community/async-storage@"1.12.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.13.1" from react-native@0.63.4
npm ERR! node_modules/react-native
npm ERR!   react-native@"0.63.4" from the root project
npm ERR!   peer react-native@">=0.59" from @react-native-community/async-storage@1.12.1
npm ERR!   node_modules/@react-native-community/async-storage
npm ERR!     @react-native-community/async-storage@"1.12.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

Many thanks,
Alex

**Comment by liplylie** [comment]
Hi Alex,

Could you try some of the methods in this link? https://stackoverflow.com/questions/64573177/unable-to-resolve-dependency-tree-error-when-installing-npm-packages

For example, please try running:
```
npm install --save --legacy-peer-deps
```
or try a different version of node:
```
nvm use 12
```

**Comment by alexchudnovsky** [comment]
Hi Jordan,

Thanks for your reply 

Yes sure, I will try both methods, will let you know how I go 

Cheers,
Alex

**Comment by alexchudnovsky** [comment]
Hi Jordan, 

I have just tried the below

alexchudnovsky:example/ $ nvm use 12                                                                                                                                                                   [15:14:59]
Now using node v12.14.1 (npm v6.13.4)
alexchudnovsky:example/ $ npm install                                                                                                                                                                  [15:15:30]
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "link:": link:../

Now it seems that this is the issue 
**npm ERR! Unsupported URL Type "link:": link:../**


Cheers,
Alex

**Comment by liplylie** [comment]
Can you try yarn install instead of npm?

https://github.com/AM-77/react-datepickerrz/issues/2#issuecomment-625497669

**Comment by alexchudnovsky** [comment]
Yes sure, trying now

**Comment by alexchudnovsky** [comment]
Thanks very much for your help, it's all working now :)

**Comment by liplylie** [comment]
You're welcome :)
