### ISSUE TITLE
error on delete alarm by id

### ISSUE THREAD

**Issue by matheusf31** [liplylie/react-native-simple-alarm#4]
I have the next error when i try to delete a alarm by id:

`Error: Please enter an alarm id`

but i confirmed that i am sending the id correctly.

**Comment by matheusf31** [comment]
I found the problem! In your documentation of method deleteAlarmById you have:

```
import { deleteAlarm } from 'react-native-simple-alarm'; <---- PROBLEM

deleteAlarmById = async () => {
  let id = '07699912-87d9-11ea-bc55-0242ac130003';
  
  try {
    await deleteAlarm(id);    <--- PROBLEM
  } catch (e) {}
}
```
The correct would be deleteAlarmById()

**Comment by liplylie** [comment]
@matheusf31 Good catch, I'll update the read me.
