### ISSUE TITLE
Add Home Automation Feature

### ISSUE THREAD

**Issue by csimlinger** [liplylie/react-native-simple-alarm#6]
Great app! I found it while I was searching for an alarm clock that can be combined with home automation. Seems like there is nothing like that. So I wanted to make the suggestion here:

It would be awesome to implement a feature to trigger a smart home switch or to trigger an API request.
The idea is to set an alarm via an alarm clock to trigger a task once the alarm goes off. 

Any chance you could implement a feature like that? 😃 

Thanks!

**Comment by liplylie** [comment]
Cool idea. triggering a smart home switch would be beyond the scope of this project though.

Shouldn't be too much work to trigger an api request with an alarm change. Could just make the api request after an alarm change.

Could probably build a smart home switch using [react-native-ble-plx]. 

[react-native-ble-plx]: https://github.com/Polidea/react-native-ble-plx

**Comment by csimlinger** [comment]
That would be greatly appreciated and solve a currently unsolvable problem for me! 🙌
Even cooler if it would be possible to toggle the switch X minutes before the alarm goes off. Then you could make an alarm saying 30 minutes before the alarm goes off, turn on the switch (which is connected to the coffee machine, light...).
That would be an amazing improvement!
