### ISSUE TITLE
Does the alarm sound even in silent mode?

### ISSUE THREAD

**Issue by daheeahn** [liplylie/react-native-simple-alarm#8]
Hi :)

I'm making an alarm app, but the alarm rings even in silent mode?
In this library you are using, there is no way to sound an alarm in silent mode. [issue](https://github.com/zo0r/react-native-push-notification/issues/1546)
Is this possible? I haven't installed this library yet, but if it works, I will install it and use it

**Comment by liplylie** [comment]
closing as you found a workaround for this: https://github.com/zo0r/react-native-push-notification/issues/1584#issuecomment-671381806
