### ISSUE TITLE
Trying to edit snooze in the example

### ISSUE THREAD

**Issue by franciscocamellon** [liplylie/react-native-simple-alarm#9]
### I installed the example and try to edit snooze and give this error:

![Screenshot_1600858959](https://user-images.githubusercontent.com/38926687/94004756-8dc84480-fd73-11ea-9d08-a79f0afc9d9a.png)

**Comment by liplylie** [comment]
@franciscocamellon can you show a code example?

Also, snooze can only be a number.

**Comment by liplylie** [comment]
closing for now
